/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import DAO.DanhSachSPDAO;
import DAO.SanPhamDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import entity.SanPham;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author ASUS
 */
public class SanPhamJrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form SanPham
     */
    public SanPhamJrame() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        pnlDanhMucSanPham = new javax.swing.JPanel();
        pnlPhanLoaiNhomHang = new javax.swing.JPanel();
        lblMaLoaiGiay = new javax.swing.JLabel();
        lblTenLoaiGiay = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        txtMaLoaiGiay = new javax.swing.JTextField();
        txtTenLoaiGiay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChuHang = new javax.swing.JTextArea();
        btnThemHang = new javax.swing.JButton();
        btnCapNhatHang = new javax.swing.JButton();
        btnXoaHang = new javax.swing.JButton();
        btnResetHang = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhanLoaiGiay = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtThuongHieu = new javax.swing.JTextField();
        pnlPhanLoaiHang = new javax.swing.JPanel();
        cboLoaiGiay = new javax.swing.JComboBox<>();
        lblPhanLoaiHang = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblHinhSP = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        txtTimKiemSP = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblDanhSachSP = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        btnThemSP = new javax.swing.JButton();
        btnCapNhatSP = new javax.swing.JButton();
        btnMoiSP = new javax.swing.JButton();
        lblMaSP = new javax.swing.JLabel();
        lblTenSP = new javax.swing.JLabel();
        lblSoLuongTon = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtSoLuongTonKho = new javax.swing.JTextField();
        lblDonGia1 = new javax.swing.JLabel();
        txtChatLieu = new javax.swing.JTextField();
        lblDonGia2 = new javax.swing.JLabel();
        txtMauSac = new javax.swing.JTextField();
        lblDonGia3 = new javax.swing.JLabel();
        txtKichCo = new javax.swing.JTextField();
        txtTenTH = new javax.swing.JLabel();
        txtThuongHieuSP = new javax.swing.JTextField();
        btnXoaHang1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 624));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1261, 624));

        pnlDanhMucSanPham.setBackground(new java.awt.Color(0, 153, 255));

        pnlPhanLoaiNhomHang.setBackground(new java.awt.Color(0, 153, 255));

        lblMaLoaiGiay.setForeground(new java.awt.Color(255, 255, 255));
        lblMaLoaiGiay.setText("Mã giày:");

        lblTenLoaiGiay.setForeground(new java.awt.Color(255, 255, 255));
        lblTenLoaiGiay.setText("Tên giày:");

        lblGhiChu.setForeground(new java.awt.Color(255, 255, 255));
        lblGhiChu.setText("Ghi chú: ");

        txtGhiChuHang.setColumns(20);
        txtGhiChuHang.setRows(5);
        jScrollPane1.setViewportView(txtGhiChuHang);

        btnThemHang.setBackground(new java.awt.Color(0, 255, 0));
        btnThemHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThemHang.setText("Thêm");

        btnCapNhatHang.setBackground(new java.awt.Color(255, 255, 51));
        btnCapNhatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnCapNhatHang.setText("Cập nhật");

        btnXoaHang.setBackground(new java.awt.Color(255, 102, 102));
        btnXoaHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoaHang.setText("Xóa");

        btnResetHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Document.png"))); // NOI18N
        btnResetHang.setText("Mới");

        tblPhanLoaiGiay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã giày", "Tên giày", "Thương hiệu", "Ghi chú"
            }
        ));
        jScrollPane2.setViewportView(tblPhanLoaiGiay);

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Thương hiệu:");

        javax.swing.GroupLayout pnlPhanLoaiNhomHangLayout = new javax.swing.GroupLayout(pnlPhanLoaiNhomHang);
        pnlPhanLoaiNhomHang.setLayout(pnlPhanLoaiNhomHangLayout);
        pnlPhanLoaiNhomHangLayout.setHorizontalGroup(
            pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhanLoaiNhomHangLayout.createSequentialGroup()
                .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhanLoaiNhomHangLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblGhiChu)
                            .addComponent(lblTenLoaiGiay)
                            .addComponent(lblMaLoaiGiay))
                        .addGap(32, 32, 32)
                        .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaLoaiGiay)
                            .addComponent(txtTenLoaiGiay)
                            .addComponent(txtThuongHieu)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)))
                    .addGroup(pnlPhanLoaiNhomHangLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnThemHang, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhatHang)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaHang)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetHang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPhanLoaiNhomHangLayout.setVerticalGroup(
            pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhanLoaiNhomHangLayout.createSequentialGroup()
                .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPhanLoaiNhomHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPhanLoaiNhomHangLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaLoaiGiay)
                            .addComponent(txtMaLoaiGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenLoaiGiay)
                            .addComponent(txtTenLoaiGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGhiChu)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(pnlPhanLoaiNhomHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnResetHang)
                            .addComponent(btnXoaHang)
                            .addComponent(btnCapNhatHang)
                            .addComponent(btnThemHang))))
                .addGap(25, 25, 25))
        );

        pnlPhanLoaiHang.setBackground(new java.awt.Color(0, 153, 255));
        pnlPhanLoaiHang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cboLoaiGiay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adidas", "Nike", "Puma", "Converse", " " }));

        javax.swing.GroupLayout pnlPhanLoaiHangLayout = new javax.swing.GroupLayout(pnlPhanLoaiHang);
        pnlPhanLoaiHang.setLayout(pnlPhanLoaiHangLayout);
        pnlPhanLoaiHangLayout.setHorizontalGroup(
            pnlPhanLoaiHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhanLoaiHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboLoaiGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPhanLoaiHangLayout.setVerticalGroup(
            pnlPhanLoaiHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhanLoaiHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboLoaiGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPhanLoaiHang.setFont(new java.awt.Font("Raleway Medium", 1, 14)); // NOI18N
        lblPhanLoaiHang.setForeground(new java.awt.Color(255, 255, 255));
        lblPhanLoaiHang.setText("Thương hiệu");

        javax.swing.GroupLayout pnlDanhMucSanPhamLayout = new javax.swing.GroupLayout(pnlDanhMucSanPham);
        pnlDanhMucSanPham.setLayout(pnlDanhMucSanPhamLayout);
        pnlDanhMucSanPhamLayout.setHorizontalGroup(
            pnlDanhMucSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhMucSanPhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPhanLoaiHang)
                .addGap(26, 26, 26)
                .addComponent(pnlPhanLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(pnlDanhMucSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPhanLoaiNhomHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlDanhMucSanPhamLayout.setVerticalGroup(
            pnlDanhMucSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhMucSanPhamLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlDanhMucSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPhanLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhanLoaiHang))
                .addGap(18, 18, 18)
                .addComponent(pnlPhanLoaiNhomHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        tabs.addTab("Danh mục sản phẩm", pnlDanhMucSanPham);

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jPanel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblHinhSP.setText("jLabel27");
        lblHinhSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhSPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinhSP, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHinhSP, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(242, 242, 242));
        jLabel25.setText("Tìm kiếm");

        jPanel15.setBackground(new java.awt.Color(0, 153, 255));
        jPanel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemSP, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblDanhSachSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng tồn kho", "Đơn giá", "Chất liệu", "Màu sắc", "Kích cỡ", "Mã NCC", "Thương hiệu", "Ảnh"
            }
        ));
        tblDanhSachSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSPMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tblDanhSachSP);

        jPanel12.setBackground(new java.awt.Color(51, 153, 255));
        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setForeground(new java.awt.Color(242, 242, 242));

        btnThemSP.setBackground(new java.awt.Color(51, 255, 51));
        btnThemSP.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnThemSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThemSP.setText("Thêm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnCapNhatSP.setBackground(new java.awt.Color(255, 255, 51));
        btnCapNhatSP.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnCapNhatSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnCapNhatSP.setText("Cập nhật");
        btnCapNhatSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatSPActionPerformed(evt);
            }
        });

        btnMoiSP.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnMoiSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Document.png"))); // NOI18N
        btnMoiSP.setText("Mới");
        btnMoiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiSPActionPerformed(evt);
            }
        });

        lblMaSP.setForeground(new java.awt.Color(242, 242, 242));
        lblMaSP.setText("Mã sản phẩm:");

        lblTenSP.setForeground(new java.awt.Color(242, 242, 242));
        lblTenSP.setText("Tên sản phẩm: ");

        lblSoLuongTon.setForeground(new java.awt.Color(242, 242, 242));
        lblSoLuongTon.setText("Số lượng tồn kho:");

        lblDonGia.setForeground(new java.awt.Color(242, 242, 242));
        lblDonGia.setText("Đơn giá:");

        lblDonGia1.setForeground(new java.awt.Color(242, 242, 242));
        lblDonGia1.setText("Chất liệu:");

        lblDonGia2.setForeground(new java.awt.Color(242, 242, 242));
        lblDonGia2.setText("Màu sắc:");

        lblDonGia3.setForeground(new java.awt.Color(242, 242, 242));
        lblDonGia3.setText("Kích cỡ:");

        txtTenTH.setForeground(new java.awt.Color(242, 242, 242));
        txtTenTH.setText("Thương hiệu:");

        btnXoaHang1.setBackground(new java.awt.Color(255, 102, 102));
        btnXoaHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoaHang1.setText("Xóa");
        btnXoaHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHang1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Mã NCC:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(lblSoLuongTon)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                            .addComponent(txtSoLuongTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(lblTenSP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(lblMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnThemSP, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(btnXoaHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCapNhatSP, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(btnMoiSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDonGia1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDonGia)
                            .addComponent(lblDonGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDonGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(txtTenTH, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKichCo, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txtMauSac, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txtChatLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txtThuongHieuSP, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(txtMaNCC))
                .addGap(71, 71, 71))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaSP)
                    .addComponent(lblDonGia)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenSP)
                    .addComponent(lblDonGia1)
                    .addComponent(txtChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoLuongTon)
                    .addComponent(txtSoLuongTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonGia2)
                    .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemSP)
                            .addComponent(btnMoiSP)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonGia3)
                            .addComponent(txtKichCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoaHang1)
                            .addComponent(btnCapNhatSP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenTH)
                            .addComponent(txtThuongHieuSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel25))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        tabs.addTab("Sản phẩm", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1095, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 1083, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 587, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatSPActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnCapNhatSPActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void tblDanhSachSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSPMouseClicked
        // TODO add your handling code here:
        SanPham sp = new SanPham();
        row = tblDanhSachSP.getSelectedRow();
        showDetails();
    }//GEN-LAST:event_tblDanhSachSPMouseClicked

    private void btnMoiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiSPActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiSPActionPerformed

    private void btnXoaHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHang1ActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaHang1ActionPerformed

    private void lblHinhSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhSPMouseClicked
        // TODO add your handling code here:
        chonAnh();
    }//GEN-LAST:event_lblHinhSPMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatHang;
    private javax.swing.JButton btnCapNhatSP;
    private javax.swing.JButton btnMoiSP;
    private javax.swing.JButton btnResetHang;
    private javax.swing.JButton btnThemHang;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnXoaHang;
    private javax.swing.JButton btnXoaHang1;
    private javax.swing.JComboBox<String> cboLoaiGiay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblDonGia1;
    private javax.swing.JLabel lblDonGia2;
    private javax.swing.JLabel lblDonGia3;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblHinhSP;
    private javax.swing.JLabel lblMaLoaiGiay;
    private javax.swing.JLabel lblMaSP;
    private javax.swing.JLabel lblPhanLoaiHang;
    private javax.swing.JLabel lblSoLuongTon;
    private javax.swing.JLabel lblTenLoaiGiay;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JPanel pnlDanhMucSanPham;
    private javax.swing.JPanel pnlPhanLoaiHang;
    private javax.swing.JPanel pnlPhanLoaiNhomHang;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblDanhSachSP;
    private javax.swing.JTable tblPhanLoaiGiay;
    private javax.swing.JTextField txtChatLieu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextArea txtGhiChuHang;
    private javax.swing.JTextField txtKichCo;
    private javax.swing.JTextField txtMaLoaiGiay;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextField txtSoLuongTonKho;
    private javax.swing.JTextField txtTenLoaiGiay;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JLabel txtTenTH;
    private javax.swing.JTextField txtThuongHieu;
    private javax.swing.JTextField txtThuongHieuSP;
    private javax.swing.JTextField txtTimKiemSP;
    // End of variables declaration//GEN-END:variables

    SanPhamDAO dao = new SanPhamDAO();
    DanhSachSPDAO dsdao = new DanhSachSPDAO();
    int row = -1;
    
    void init(){
       // this.fillTablePhanLoai();
        this.fillTableSanPham();
    }
    void insert() {
        SanPham model = getForm();
        if(!Validate()){
            return;
        }else{
            try {
                dao.insert(model);
                this.fillTableSanPham();
                this.setForm(model);
                JOptionPane.showMessageDialog(this, "Thêm mới thành công !");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Thêm mới thất bại !");
                e.printStackTrace();
            }
        }
    }

    void fillTableSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSachSP.getModel();
        model.setRowCount(0);
        try {
            SanPham sanpham = new SanPham();
            List<SanPham> list = dao.selectAll();
            for (SanPham sp : list) {
                Object[] row = {
                    sp.getMaSP(),
                    sp.getTenSP(),
                    sp.getSoLuongTonKho(),
                    sp.getDonGia(),
                    sp.getChatLieu(),
                    sp.getMauSac(),
                    sp.getKichCo(),
                    sp.getMaNCC(),
                    sp.getThuongHieu(),
                    sp.getHinhSP(),
                };
                model.addRow(row);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu: "+e.getMessage());
            e.printStackTrace();
        }
    }
    void fillTablePhanLoai() {
        DefaultTableModel model = (DefaultTableModel) tblPhanLoaiGiay.getModel();
        model.setRowCount(0);
        try {
            SanPham sanpham = new SanPham();
            List<SanPham> list = dsdao.selectByDSSP(sanpham.getMaSP());
            for (SanPham sp : list) {
                Object[] row = {
                    sp.getMaSP(),
                    sp.getTenSP(),
                    sp.getThuongHieu(),
                    sp.getGhiChu()
                };
                model.addRow(row);
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu");
        }
    }
    void clearForm(){
        SanPham sp = new SanPham();
        this.setForm(sp);
        row = -1;
        
    }

    void setForm(SanPham sp) {
        txtMaSP.setText(sp.getMaSP());
        txtTenSP.setText(sp.getTenSP());
        txtSoLuongTonKho.setText(String.valueOf(sp.getSoLuongTonKho()));
        txtDonGia.setText(String.valueOf(sp.getDonGia()));
        txtChatLieu.setText(sp.getChatLieu());
        txtMauSac.setText(sp.getMauSac());
        txtKichCo.setText(String.valueOf(sp.getKichCo()));
        txtMaNCC.setText(sp.getMaNCC());
        txtThuongHieuSP.setText(sp.getThuongHieu());
    }

    SanPham getForm() {
        SanPham sp = new SanPham();
        sp.setMaSP(txtMaSP.getText());
        sp.setTenSP(txtTenSP.getText());
        sp.setSoLuongTonKho(Integer.valueOf(txtSoLuongTonKho.getText()));
        sp.setDonGia(Double.valueOf(txtDonGia.getText()));
        sp.setChatLieu(txtChatLieu.getText());
        sp.setMauSac(txtMauSac.getText());
        sp.setKichCo(Integer.valueOf(txtKichCo.getText()));
        sp.setMaNCC(txtMaNCC.getText());
        sp.setThuongHieu(txtThuongHieuSP.getText());
        return sp;
        
    }

    boolean Validate() {
        if(txtMaSP.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Mã sản phẩm đang trống !");
            return false;
        }else if(txtTenSP.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Tên sản phẩm đang trống !");
            return false;
        }else if(txtSoLuongTonKho.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Số lượng tồn kho đang trống !");
            return false;
        }else if(txtDonGia.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Đơn giá đang trống !");
            return false;
        }else if(txtChatLieu.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Chất liệu đang trống !");
            return false;
        }else if(txtMauSac.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Màu sắc đang trống !");
            return false;
        }else if(txtKichCo.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Kích cỡ đang trống !");
            return false;
        }else if(txtMaNCC.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Mã nhà cung cấp đang trống !");
            return false;
        }else if(txtThuongHieuSP.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Thương hiệu đang trống !");
            return false;
        }
        return true;
    }
    
    void update(){
        SanPham model = getForm();
        try {
            dao.update(model);
            this.fillTableSanPham();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại !");
            e.printStackTrace();
        }
    }
    void delete() {
        
    }
    
    private void showDetails() {
        txtMaSP.setText(tblDanhSachSP.getValueAt(row, 0).toString());
        txtTenSP.setText(tblDanhSachSP.getValueAt(row, 1).toString());
        txtSoLuongTonKho.setText(tblDanhSachSP.getValueAt(row, 2).toString());
        txtDonGia.setText(tblDanhSachSP.getValueAt(row, 3).toString());
        txtChatLieu.setText(tblDanhSachSP.getValueAt(row, 4).toString());
        txtMauSac.setText(tblDanhSachSP.getValueAt(row, 5).toString());
        txtKichCo.setText(tblDanhSachSP.getValueAt(row, 6).toString());
        txtMaNCC.setText(tblDanhSachSP.getValueAt(row, 7).toString());
        txtThuongHieuSP.setText(tblDanhSachSP.getValueAt(row, 8).toString());
        
    }

    void chonAnh() {
        
    }

    

    
}
